object Versions {
    const val kotlinVersion = "1.7.0"
    const val gradleVersion = "7.0.2"
    const val appcompatVersion = "1.4.0"
    const val materialVersion = "1.5.0-rc01"
    const val constraintLayoutVersion = "2.1.2"
    const val junitVersion = "1.1.3"
    const val espressoCoreVersion = "3.4.0"
    const val retrofitVersion = "2.9.0"
    const val roomVersion = "2.4.0"
    const val roomPagingVersion = "2.4.0-rc01"
    const val navigationVersion = "2.3.5"
    const val glideVersion = "4.12.0"
    const val lifecycleVersion = "2.4.0"
    const val fragmentVersion = "1.4.0"
    const val hiltVersion = "2.38.1"
    const val coroutinesVersion = "1.6.0-RC"
    const val lottieVersion = "4.2.2"
    const val scalableSizeUnitVersion = "1.0.6"
    const val pagingVersion = "3.1.0"
}